image: node:12
cache:
  paths:
    - node_modules/

before_script:
  - npm install -g documentation
  - npm ci

pages:
  script:
    - documentation build lib/index.js -f html -o public
  artifacts:
    paths:
      - public/
  only:
    - master
